#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EN_Lab_11_PizzaComposer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB")]
	public partial class DBPizzaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertIngerdient(Ingerdient instance);
    partial void UpdateIngerdient(Ingerdient instance);
    partial void DeleteIngerdient(Ingerdient instance);
    partial void InsertPizza(Pizza instance);
    partial void UpdatePizza(Pizza instance);
    partial void DeletePizza(Pizza instance);
    #endregion
		
		public DBPizzaDataContext() : 
				base(global::EN_Lab_11_PizzaComposer.Properties.Settings.Default.DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBPizzaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPizzaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPizzaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBPizzaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ingerdient> Ingerdients
		{
			get
			{
				return this.GetTable<Ingerdient>();
			}
		}
		
		public System.Data.Linq.Table<Pizza> Pizzas
		{
			get
			{
				return this.GetTable<Pizza>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ingerdient")]
	public partial class Ingerdient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private int _PizzaId;
		
		private EntityRef<Pizza> _Pizza;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPizzaIdChanging(int value);
    partial void OnPizzaIdChanged();
    #endregion
		
		public Ingerdient()
		{
			this._Pizza = default(EntityRef<Pizza>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PizzaId", DbType="Int NOT NULL")]
		public int PizzaId
		{
			get
			{
				return this._PizzaId;
			}
			set
			{
				if ((this._PizzaId != value))
				{
					if (this._Pizza.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPizzaIdChanging(value);
					this.SendPropertyChanging();
					this._PizzaId = value;
					this.SendPropertyChanged("PizzaId");
					this.OnPizzaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pizza_Ingerdient", Storage="_Pizza", ThisKey="PizzaId", OtherKey="Id", IsForeignKey=true)]
		public Pizza Pizza
		{
			get
			{
				return this._Pizza.Entity;
			}
			set
			{
				Pizza previousValue = this._Pizza.Entity;
				if (((previousValue != value) 
							|| (this._Pizza.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pizza.Entity = null;
						previousValue.Ingerdients.Remove(this);
					}
					this._Pizza.Entity = value;
					if ((value != null))
					{
						value.Ingerdients.Add(this);
						this._PizzaId = value.Id;
					}
					else
					{
						this._PizzaId = default(int);
					}
					this.SendPropertyChanged("Pizza");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pizza")]
	public partial class Pizza : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private char _Size;
		
		private bool _Sauce;
		
		private EntitySet<Ingerdient> _Ingerdients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSizeChanging(char value);
    partial void OnSizeChanged();
    partial void OnSauceChanging(bool value);
    partial void OnSauceChanged();
    #endregion
		
		public Pizza()
		{
			this._Ingerdients = new EntitySet<Ingerdient>(new Action<Ingerdient>(this.attach_Ingerdients), new Action<Ingerdient>(this.detach_Ingerdients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NChar(1) NOT NULL")]
		public char Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sauce", DbType="Bit NOT NULL")]
		public bool Sauce
		{
			get
			{
				return this._Sauce;
			}
			set
			{
				if ((this._Sauce != value))
				{
					this.OnSauceChanging(value);
					this.SendPropertyChanging();
					this._Sauce = value;
					this.SendPropertyChanged("Sauce");
					this.OnSauceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pizza_Ingerdient", Storage="_Ingerdients", ThisKey="Id", OtherKey="PizzaId")]
		public EntitySet<Ingerdient> Ingerdients
		{
			get
			{
				return this._Ingerdients;
			}
			set
			{
				this._Ingerdients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ingerdients(Ingerdient entity)
		{
			this.SendPropertyChanging();
			entity.Pizza = this;
		}
		
		private void detach_Ingerdients(Ingerdient entity)
		{
			this.SendPropertyChanging();
			entity.Pizza = null;
		}
	}
}
#pragma warning restore 1591
