<?xml version="1.0" encoding="utf-8"?><Database Name="DB" Class="DBPizzaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="EN_Lab_11_PizzaComposer.Properties.Settings" SettingsPropertyName="DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ingerdient" Member="Ingerdients">
    <Type Name="Ingerdient">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PizzaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pizza_Ingerdient" Member="Pizza" ThisKey="PizzaId" OtherKey="Id" Type="Pizza" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pizza" Member="Pizzas">
    <Type Name="Pizza">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Sauce" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Pizza_Ingerdient" Member="Ingerdients" ThisKey="Id" OtherKey="PizzaId" Type="Ingerdient" />
    </Type>
  </Table>
</Database>